services:
  - type: static
    name: your-app-name
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - source: /*
        headers:
          - name: Cache-Control
            value: no-cache
    redirects:
      - source: /*
        destination: /index.html
        status: 200
